import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {cohort,districtLayout,LANDMARK_SIZE} from '../src/district/model.js';
const snapshot=JSON.parse(fs.readFileSync(new URL('../src/fullcity/wallets.json',import.meta.url))),wallets=cohort(snapshot);
test('384 distinct eligible real wallets are identical in both design layouts',()=>{assert.equal(wallets.length,384);assert.equal(new Set(wallets.map(w=>w.a)).size,384);assert.ok(wallets.every(w=>snapshot.wallets.some(s=>s.a===w.a&&s.res!==false)));const a=districtLayout(wallets,'compact'),b=districtLayout(wallets,'garden');assert.deepEqual(a.homes.map(({x,z,block,...w})=>w),b.homes.map(({x,z,block,...w})=>w));assert.ok(a.area>b.area);assert.equal(a.blocks.length,41);assert.equal(b.blocks.length,18);});
test('landmark widths are independent of the old thin production envelopes',()=>{assert.equal(wallets.filter(w=>w.landmark).length,12);assert.ok(wallets[0].width>6);assert.ok(wallets[1].width>4);for(const [height,width]of LANDMARK_SIZE){assert.ok(height>width);assert.ok(width<=7);}});
test('housing frontages and tree trunks have room within their sidewalk blocks',()=>{for(const key of ['compact','garden']){const l=districtLayout(wallets,key);for(const w of l.homes.slice(12)){const b=typeof w.block==='number'?l.blocks[w.block]:l.landmarkBlocks.find(b=>b.id===w.block);assert.ok(Math.abs(w.x-b.x)+.8<b.w/2);assert.ok(Math.abs(w.z-b.z)+1.05<b.d/2);}for(const t of l.treeSites){const b=l.blocks[t.block];assert.ok(Math.abs(t.x-b.x)+.4<=b.w/2);assert.ok(Math.abs(t.z-b.z)+.4<=b.d/2);}}});

test('distributed landmark parcels share the street grid without displacing or overlapping homes',()=>{for(const key of ['compact','garden']){const l=districtLayout(wallets,key),parcels=[...l.blocks,...l.landmarkBlocks,...l.gardens];assert.equal(new Set(parcels.map(b=>b.cell)).size,l.rows*l.cols);assert.equal(parcels.length,l.rows*l.cols);assert.ok(new Set(l.landmarkBlocks.map(b=>Math.floor(b.cell/l.cols))).size>=5);l.landmarkBlocks.forEach((b,i)=>{assert.equal(l.homes[i].x,b.x);assert.equal(l.homes[i].z,b.z);assert.ok(l.homes[i].width+1.5<Math.min(b.w,b.d));});for(let i=0;i<parcels.length;i++)for(let j=i+1;j<parcels.length;j++){const a=parcels[i],b=parcels[j];assert.ok(Math.abs(a.x-b.x)>=(a.w+b.w)/2+l.road-.001||Math.abs(a.z-b.z)>=(a.d+b.d)/2+l.road-.001);}}});

test('Manhattan has high-rise forms and the specified real companion wallets on each landmark block',()=>{for(const key of ['compact','garden']){const l=districtLayout(wallets,key);assert.ok(l.homes.slice(12).every(w=>w.h>=7&&['glass','concrete'].includes(w.identity.family)));for(const b of l.landmarkBlocks)assert.equal(l.homes.filter(w=>w.block===b.id).length,1+l.companions);for(let i=0;i<l.homes.length;i++)for(let j=i+1;j<l.homes.length;j++){const a=l.homes[i],b=l.homes[j],aw=a.width||a.identity.width+.12,ad=a.width||a.identity.depth+.3,bw=b.width||b.identity.width+.12,bd=b.width||b.identity.depth+.3;assert.ok(Math.abs(a.x-b.x)>=(aw+bw)/2||Math.abs(a.z-b.z)>=(ad+bd)/2,`overlap ${i}/${j}`);}}});

test('eight-tower option expands land without resizing or inventing wallets',()=>{const a=districtLayout(wallets,'compact'),b=districtLayout(wallets,'garden');assert.equal(a.perBlock,8);assert.equal(b.perBlock,16);assert.equal(a.blockW,b.blockW);assert.equal(a.blockD,b.blockD);for(const l of [a,b])for(const block of l.blocks)assert.ok(l.homes.filter(w=>w.block===block.id).length<=l.perBlock);assert.equal(a.homes.length,b.homes.length);assert.ok(a.area/b.area>1.5);});
