import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {cohort} from '../src/district/model.js';import {geographicLayout,bridgeConnections} from '../src/district/geography.js';import {placeCity,cityScale,pointInRing} from '../src/fullcity/city-map.js';
const snapshot=JSON.parse(fs.readFileSync(new URL('../src/fullcity/wallets.json',import.meta.url))),wallets=cohort(snapshot,true),original=placeCity(wallets,cityScale(wallets.length)),layouts=['compact','garden'].map(k=>geographicLayout(wallets,k));
test('geography preserves every wallet, score, flow and existing neighborhood assignment',()=>{for(const l of layouts){assert.equal(l.homes.length,wallets.length);assert.equal(new Set(l.homes.map(w=>w.a)).size,wallets.length);for(let i=0;i<wallets.length;i++){const w=l.homes[i];assert.equal(w.a,original[i].a);assert.equal(w.hood,original[i].hood.id??original[i].hood);assert.equal(w.score,original[i].score);assert.equal(w.flow,original[i].flow);assert.ok(w.h>0);if(i<12){assert.equal(w.h,wallets[i].h);assert.equal(w.width,wallets[i].width);}}}});
test('every wallet retains its original position after the uniform map transform',()=>{for(const l of layouts){for(let i=0;i<original.length;i++){const expected=l.project(original[i].x/cityScale(wallets.length),original[i].z/cityScale(wallets.length));assert.ok(Math.abs(l.homes[i].x-expected.x)<1e-8);assert.ok(Math.abs(l.homes[i].z-expected.z)<1e-8);}assert.equal(new Set(l.blocks.map(b=>b.id)).size,l.blocks.length);assert.ok(l.blocks.every(b=>b.homes.length>0));assert.equal(l.gardens.length,0);assert.ok(l.streets.length>0);assert.ok(l.shoreGardens.length>0);}});
test('landmarks keep their proportions and clear all neighboring wallet footprints',()=>{for(const l of layouts)for(const a of l.homes.slice(0,12))for(const b of l.homes.slice(12))assert.ok(Math.abs(a.x-b.x)>=(a.width+b.identity.width)/2||Math.abs(a.z-b.z)>=(a.width+b.identity.depth)/2);});
test('density options share geography scale and preserve landmark dimensions while outer boroughs are lower-rise',()=>{assert.equal(layouts[0].geoScale,layouts[1].geoScale);for(const l of layouts){for(const w of l.homes.filter(w=>w.borough!=='manhattan'&&!w.landmark))assert.ok(w.h<8);assert.equal(l.homes.filter(w=>w.landmark).length,12);}});

test('both bridge approaches connect to on-land street corners',()=>{for(const l of layouts){const links=bridgeConnections(l);assert.equal(links.length,2);for(const {start,end} of links)assert.ok(Math.hypot(end.x-start.x,end.z-start.z)<20);}});

test('Liberty Island site remains water in the simplified harbor coastline',()=>{for(const l of layouts)assert.ok(!Object.values(l.land).some(rings=>rings.some(r=>pointInRing(l.harbor.x,l.harbor.z,r))));});
