import React,{useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {SILHOUETTES,silhouetteParts,MANHATTAN_FAMILIES} from './district/silhouettes.js';
import './catalogue.css';
const groups=['All families','Expressive high-rise','Ordinary tower','Mid-rise / residential','Low-rise / special'];
export default function Catalogue(){
 const mount=useRef(),engine=useRef(),[images,setImages]=useState([]),[selected,setSelected]=useState(0),[variant,setVariant]=useState(0),[filter,setFilter]=useState('All families');
 useEffect(()=>{const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.4));renderer.setSize(240,250);renderer.setClearColor(0x263332);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
 const scene=new THREE.Scene();scene.add(new THREE.HemisphereLight(0xffffff,0x677366,2));const sun=new THREE.DirectionalLight(0xfff0d7,3);sun.position.set(-10,20,15);scene.add(sun);const fill=new THREE.DirectionalLight(0xb4d4df,1);fill.position.set(10,4,-10);scene.add(fill);
 const camera=new THREE.PerspectiveCamera(32,240/250,.1,100),material=new THREE.MeshStandardMaterial({color:0xd5d3c7,roughness:.8}),baseMat=new THREE.MeshStandardMaterial({color:0x62716a,roughness:1}),base=new THREE.Mesh(new THREE.CylinderGeometry(2.3,2.3,.13,48),baseMat);base.position.y=-.1;scene.add(base);
 let group=null;const clear=()=>{if(group){group.traverse(o=>o.geometry?.dispose());scene.remove(group);}};
 const show=(id,v=0)=>{clear();group=new THREE.Group();const f=SILHOUETTES[id],height=f.group==='Low-rise / special'?3.2:f.group==='Mid-rise / residential'?6:11;for(const {geometry}of silhouetteParts(id,{width:2.3+(v-1)*.22,depth:2.5,height:height*(1+v*.06),variant:v}))group.add(new THREE.Mesh(geometry,material));scene.add(group);camera.position.set(13,13,18);camera.lookAt(0,5,0);renderer.render(scene,camera);return height;};
 const thumbnails=SILHOUETTES.map(f=>{show(f.id);return renderer.domElement.toDataURL('image/png');});setImages(thumbnails);mount.current.appendChild(renderer.domElement);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=45;controls.target.set(0,5,0);
 engine.current={show(id,v){const h=show(id,v);controls.target.set(0,h/2,0);camera.position.set(13,h*.65+7,20);controls.update();}};engine.current.show(0,0);
 const resize=()=>{const {clientWidth:w,clientHeight:h}=mount.current;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}};const ro=new ResizeObserver(resize);ro.observe(mount.current);resize();let raf;const tick=()=>{raf=requestAnimationFrame(tick);if(!document.hidden){controls.update();renderer.render(scene,camera);}};tick();return()=>{cancelAnimationFrame(raf);ro.disconnect();controls.dispose();clear();base.geometry.dispose();baseMat.dispose();material.dispose();renderer.dispose();renderer.domElement.remove();};
 },[]);
 useEffect(()=>{engine.current?.show(selected,variant);},[selected,variant]);
 const f=SILHOUETTES[selected];
 return <main className="catalogue"><header><div><span>SPX CITY / SILHOUETTE LIBRARY 01</span><h1>Identity starts with the shape.</h1></div><a href="/?district=1">Explore the 384-wallet city ↗</a></header><p className="catalogue-intro">50 base families in one neutral material. Select a family to orbit its geometry and compare three bounded variations. Cards share the same camera scale; low-rise families stay low.</p><div className="catalogue-layout"><section><nav aria-label="Family categories">{groups.map(g=><button aria-pressed={filter===g} onClick={()=>setFilter(g)} key={g}>{g} <small>{g==='All families'?50:SILHOUETTES.filter(f=>f.group===g).length}</small></button>)}</nav><div className="catalogue-grid">{SILHOUETTES.filter(f=>filter==='All families'||f.group===filter).map(f=><button className="family-card" aria-pressed={selected===f.id} key={f.id} onClick={()=>setSelected(f.id)}>{images[f.id]?<img src={images[f.id]} alt={`Neutral 3D silhouette of ${f.name}`}/>:<div className="thumb-loading"/>}<span>{String(f.id+1).padStart(2,'0')} / {f.name}</span><small>{f.group}</small></button>)}</div></section><aside className="family-inspector"><div ref={mount} className="family-view" aria-label="Interactive neutral silhouette: drag to orbit, scroll to zoom"/><span>{String(selected+1).padStart(2,'0')} / {f.group}</span><h2>{f.name}</h2><div className="variants">{[0,1,2].map(v=><button key={v} aria-pressed={variant===v} onClick={()=>setVariant(v)}>Variation {v+1}</button>)}</div><p>{MANHATTAN_FAMILIES.includes(selected)?'Included in the procedural Manhattan pool.':'Available to other neighborhoods or reserved for special assignments.'}</p><p>One building identity, one wallet—even when the form has multiple towers. Landmark assignment remains separate.</p><small>Variations adjust proportions; selected families also vary taper, setbacks, rounding or twist. Materials, windows and activity lighting are deliberately absent here.</small></aside></div></main>;
}
