import React,{useEffect,useRef,useState} from 'react';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import Skyline3D from './fullcity/Skyline3D.jsx';
import snapshot from './fullcity/wallets.json';
import {cityTowers} from './fullcity/activity.js';
import {cohort} from './district/model.js';
import {geographicLayout} from './district/geography.js';
import {createDistrict} from './district/renderer.js';
import './cinematic.css';
const towers=cityTowers(snapshot,30),duration=32;
function CaptureNew({done,fail}){const mount=useRef();useEffect(()=>{let alive=true,api,models=[];const loader=new GLTFLoader();Promise.all(['/models/empire-optimized.glb','/models/liberty-optimized.glb'].map(url=>loader.loadAsync(url))).then(results=>{models=results.map(r=>r.scene);if(!alive)return;const layout=geographicLayout(cohort(snapshot,true));layout.flowMax=Math.max(...towers.map(w=>Math.abs(w.flow)),1);api=createDistrict(mount.current,{compact:layout,garden:layout},models[0],{liberty:models[1],onSelect:()=>{},onStats:()=>{},onError:fail});const frames=api.cinematicFrames();api.dispose();api=null;if(alive)done(frames);}).catch(e=>alive&&fail(e.message));return()=>{alive=false;api?.dispose();models.forEach(g=>g.traverse(o=>{o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose();}));};},[]);return <div ref={mount} className="capture-new"/>;}
const ease=t=>t*t*(3-2*t);
export default function Cinematic(){const [stage,setStage]=useState('old'),[sources,setSources]=useState({}),[error,setError]=useState(''),[ready,setReady]=useState(false),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[recording,setRecording]=useState(false);const canvas=useRef(),images=useRef({}),clock=useRef(0),play=useRef(false),record=useRef(null),start=useRef(0),reduced=useRef(matchMedia('(prefers-reduced-motion: reduce)').matches);
 const original=url=>{setSources({old:url});setStage('new');};const completed=frames=>{setSources(s=>({...s,...frames}));setStage('ready');};
 useEffect(()=>{if(stage!=='ready')return;let alive=true;Promise.all(Object.entries(sources).map(([k,src])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve([k,im]);im.onerror=reject;im.src=src;}))).then(pairs=>{if(alive){images.current=Object.fromEntries(pairs);setReady(true);}}).catch(()=>setError('Could not prepare the film frames.'));return()=>{alive=false;};},[stage,sources]);
 function draw(t){const c=canvas.current;if(!c||!images.current.old)return;const g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#091211';g.fillRect(0,0,w,h);
 const shot=(key,progress,alpha=1)=>{const im=images.current[key];g.save();g.globalAlpha=alpha;const scale=Math.max(w/im.width,h/im.height)*(reduced.current?1:1.015+.045*progress),dw=im.width*scale,dh=im.height*scale;g.drawImage(im,(w-dw)/2+(reduced.current?0:progress*10),(h-dh)/2,dw,dh);g.restore();};
 if(t<9){shot('old',t/9);if(t>5){g.save();g.beginPath();g.rect(0,0,w*ease(Math.min(1,(t-5)/3)),h);g.clip();shot('manhattan',t/16);g.restore();}}
 else if(t<16){shot('manhattan',1);shot('landmarks',(t-9)/7,Math.min(1,(t-9)/1.2));}
 else if(t<23){shot('landmarks',1);shot('park',(t-16)/7,Math.min(1,(t-16)/1.2));}
 else{shot('park',1);shot('harbor',(t-23)/9,Math.min(1,(t-23)/1.2));}
 const shade=g.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(5,12,13,.28)');shade.addColorStop(.48,'rgba(5,12,13,0)');shade.addColorStop(1,'rgba(5,12,13,.84)');g.fillStyle=shade;g.fillRect(0,0,w,h);g.fillStyle='#091211';g.fillRect(0,0,w,54);g.fillRect(0,h-54,w,54);
 g.fillStyle='#c8d3bd';g.font='14px Arial';g.fillText('SPX CITY  /  A NEW PERSPECTIVE',64,34);g.textAlign='right';g.fillText(t<5?'01 / BEFORE':t<9?'THE REVEAL':'02 / SPX CITY 2.0',w-64,34);g.textAlign='left';
 let title=t<5?'It started with a wallet.':t<9?'A new city is rising.':t<16?'Every wallet. A place in the skyline.':t<23?'More life between the buildings.':'Welcome to SPX City 2.0.';
 let subtitle=t<5?'The original SPX City renderer':t<9?'The same community. A new perspective.':t<16?'Distinctive architecture. Recognisable landmarks.':t<23?'Green avenues. Living streets. A city to explore.':'Your community. Your building. Your city.';
 const cut=t<5?0:t<9?5:t<16?9:t<23?16:23;g.globalAlpha=t===0?1:Math.min(1,(t-cut)/.7+.05);g.fillStyle='#f0efe5';g.font='48px Georgia';g.fillText(title,64,h-144,w-128);g.font='20px Arial';g.fillStyle='#c6d0c5';g.fillText(subtitle,67,h-102);g.globalAlpha=1;
 g.font='12px Arial';g.fillStyle='#93a296';g.fillText('4,825 real wallets · September 7 snapshot · Original renderer → current prototype',64,h-22);g.fillStyle='#bfd0aa';g.fillRect(0,h-3,w*t/duration,3);
 }
 useEffect(()=>{if(!ready)return;let raf,previous=performance.now();const tick=now=>{if(document.hidden){previous=now;raf=requestAnimationFrame(tick);return;}if(play.current){clock.current=Math.min(duration,clock.current+(now-previous)/1000);if(clock.current>=duration){play.current=false;setPlaying(false);if(record.current?.state==='recording')record.current.stop();}}previous=now;draw(clock.current);setPosition(clock.current);raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);if(record.current?.state==='recording')record.current.stop();};},[ready]);
 const toggle=()=>{if(clock.current>=duration)clock.current=0;play.current=!play.current;setPlaying(play.current);};
 const exportFilm=()=>{try{const stream=canvas.current.captureStream(30),mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw new Error('This browser cannot export WebM video.');const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000}),chunks=[];record.current=recorder;recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const url=URL.createObjectURL(new Blob(chunks,{type:mime})),a=document.createElement('a');a.href=url;a.download='SPX-City-2.0-introduction.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setRecording(false);};clock.current=0;play.current=true;setPlaying(true);setRecording(true);recorder.start();}catch(e){setError(e.message);}};
 return <div className="city-film"><header><a href="/?district=1&geography=1">SPX CITY</a><span>2.0 / THE INTRODUCTION</span><a href="/?district=1&geography=1">{playing?'Skip intro':'Explore the city'} ↗</a></header>{stage!=='ready'&&!error?<div className="film-loading"><p>A new perspective is taking shape.</p><small>{stage==='old'?'Preparing the original city…':'Rendering the new skyline, park and harbor…'}</small><div className="film-capture">{stage==='old'?<Skyline3D towers={towers} study={false} intro={false} traffic={false} time="dusk" isMobile={false} viewH={720} onCinematicFrame={original}/>:<CaptureNew done={completed} fail={setError}/>}</div></div>:<><canvas ref={canvas} width={1280} height={720} aria-label="32-second cinematic before-and-after introduction to SPX City 2.0"/><div className="film-controls"><button disabled={!ready||recording} onClick={toggle}>{playing?'Pause':position>=duration?'Replay':'Play introduction'} <span>↗</span></button><input aria-label="Film position" type="range" min="0" max={duration} step=".1" value={position} disabled={!ready||recording} onChange={e=>{clock.current=Number(e.target.value);setPosition(clock.current);draw(clock.current);}}/><time>{Math.floor(position).toString().padStart(2,'0')} / 32s</time><button disabled={!ready||recording} onClick={exportFilm}>{recording?'Recording… keep this tab open':'Download film · WebM'}</button></div><p className="film-note">Original renderer → current prototype. Rendered city views with cinematic pans and transitions; a visual evolution, not a matched-camera comparison. Silent film · 32 seconds.{reduced.current?' Reduced-motion preference respected.':''}</p></>}{error&&<p role="alert" className="film-error">{error} <a href="/?district=1&geography=1">Return to city</a></p>}</div>;
}
