import {geographicLayout} from './district/geography.js';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import snapshot from './fullcity/wallets.json';
import {cohort,districtLayout,DESIGNS} from './district/model.js';
import {createDistrict} from './district/renderer.js';
import {LANDMARKS} from './landmarks.js';
import './district.css';
import WalletPreview from './district/WalletPreview.jsx';
const geographic=new URLSearchParams(location.search).has('geography'),full=geographic||new URLSearchParams(location.search).has('population'),wallets=cohort(snapshot,full),layouts=Object.fromEntries(Object.keys(DESIGNS).map(k=>[k,{...(geographic?geographicLayout(wallets,k):districtLayout(wallets,k)),flowMax:Math.max(...snapshot.wallets.filter(w=>w.res!==false).map(w=>Math.abs(w.d30||0)),1)}]));
const familySamples=[...new Map((geographic?layouts.compact.homes:wallets).filter(w=>!w.landmark).map(w=>[w.identity.silhouette,w])).values()].sort((a,b)=>a.identity.silhouette-b.identity.silhouette);
const fmt=n=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
export default function District({onClose}){
 const mount=useRef(),api=useRef(),[panelOpen,setPanelOpen]=useState(false),[ready,setReady]=useState(false),[exporting,setExporting]=useState(false),[error,setError]=useState(''),[key,setKey]=useState('compact'),[time,setTime]=useState('dusk'),[view,setView]=useState(geographic?'manhattan':'district'),[imported,setImported]=useState(false),[quality,setQuality]=useState(geographic),[signal,setSignal]=useState('accents'),[traffic,setTraffic]=useState(true),[selected,setSelected]=useState(null),[stats,setStats]=useState(null),[query,setQuery]=useState(''),[searchMessage,setSearchMessage]=useState('');
 useEffect(()=>{let alive=true,loaded,libertyLoaded;const init=(asset,liberty=null)=>{if(!alive)return;try{api.current=createDistrict(mount.current,layouts,asset,{onSelect:setSelected,onStats:setStats,onError:setError,liberty});if(new URLSearchParams(location.search).has('quality')){api.current.quality(true);api.current.view('quality');setView('quality');}setReady(true);}catch(e){setError(e.message);}};new GLTFLoader().load('/models/empire-optimized.glb',g=>{loaded=g.scene;if(alive){if(geographic)new GLTFLoader().load('/models/liberty-optimized.glb',g=>{if(alive){libertyLoaded=g.scene;init(loaded,libertyLoaded);}},undefined,()=>init(loaded));else init(loaded);}else loaded.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});},undefined,()=>{if(alive){setSearchMessage('Empire model unavailable; showing the authored landmark.');init(null);}});return()=>{alive=false;api.current?.dispose();libertyLoaded?.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});loaded?.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});};},[]);
 const choose=k=>{setKey(k);api.current?.layout(k);};const frame=v=>{setView(v);api.current?.view(v);};const focus=w=>{setSelected(layouts[key].homes.find(home=>home.a===w.a)||w);setView('wallet');api.current?.focus(w.a);};const find=e=>{e.preventDefault();const w=wallets.find(w=>w.a.toLowerCase()===query.trim().toLowerCase());if(w){focus(w);setSearchMessage('');}else setSearchMessage('This address is not in this preview’s wallet population.');};
 const saveComparison=async()=>{setExporting(true);await new Promise(resolve=>setTimeout(resolve,50));try{const images=api.current.comparison();const loaded=await Promise.all(images.map(x=>new Promise(resolve=>{const im=new Image();im.onload=()=>resolve({...x,im});im.src=x.url;})));const canvas=document.createElement('canvas');canvas.width=1800;canvas.height=1240;const g=canvas.getContext('2d');g.fillStyle='#182124';g.fillRect(0,0,1800,1240);g.fillStyle='#e7e7da';g.font='36px Georgia';g.fillText(`SPX City / The same ${wallets.length} wallets. Two ways to build a district.`,40,60);g.font='18px Arial';g.fillStyle='#b0bfad';g.fillText(`Identical building dimensions and camera · 12 landmarks + ${wallets.length-12} towers · September 7 snapshot`,40,98);for(let i=0;i<loaded.length;i++){const x=i*900,l=layouts[loaded[i].key];g.fillStyle='#e7e7da';g.font='28px Georgia';g.fillText(DESIGNS[l.key].name,x+30,155);g.font='17px Arial';g.fillStyle='#b0bfad';g.fillText(`${l.blocks.length} tower blocks · ${(l.area/layouts.compact.area).toFixed(2)}× land footprint`,x+30,184);const im=loaded[i].im,scale=Math.min(880/im.width,950/im.height);g.drawImage(im,x+450-im.width*scale/2,210+(950-im.height*scale)/2,im.width*scale,im.height*scale);}g.font='16px Arial';g.fillText('Design study: the layout and height treatment are proposals. Wallet data is unchanged.',40,1200);const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='spx-district-comparison.png';a.click();}catch(e){setSearchMessage('Could not export comparison: '+e.message);}finally{setExporting(false);}};
 const exportView=()=>{const a=document.createElement('a');a.href=api.current.capture();a.download=`spx-district-${key}-${view}-${time}.png`;a.click();};
 return <section className={`district-app ${panelOpen?'':'panel-collapsed'}`} role="dialog" aria-label={`${wallets.length} wallet landmark district`}>
 <header className="district-overlay-brand"><div className="district-brand"><span>EVERY WALLET. A PLACE IN THE SKYLINE.</span><h1>SPX CITY <em>2.0</em></h1></div></header>
 <button className="district-panel-toggle" aria-expanded={panelOpen} aria-controls="city-study-panel" onClick={()=>setPanelOpen(v=>!v)}>{panelOpen?'Close controls ✕':'☰ City controls'}</button><main ref={mount} className="district-stage" aria-label={`Interactive district with ${wallets.length} real wallet buildings, distributed landmarks, sidewalks and traffic`}/>
 {!ready&&<div className="district-loading" role="status">{error||'Building your district…'}</div>}
 <aside id="city-study-panel" hidden={!panelOpen} className="district-panel" onKeyDown={e=>{if(e.key==='Escape'){setPanelOpen(false);document.querySelector('.district-panel-toggle')?.focus();}}}><div className="district-panel-heading"><span className="district-eyebrow">YOUR CITY, YOUR VIEW</span><h2>City controls</h2><p>Explore neighborhoods, find your building, and set the mood.</p></div>{geographic&&<div style={{borderBottom:'1px solid #46524a',paddingBottom:16,marginBottom:18}}><span className="district-eyebrow">CITY 2.0 / ARCHITECTURAL DETAIL</span><div className="district-views" style={{margin:'8px 0'}}><button disabled={!ready} onClick={()=>frame('quality')}>Block overview ↗</button><button disabled={!ready} onClick={()=>frame('qualityStreet')}>Shopfronts ↗</button><button disabled={!ready} onClick={()=>frame('qualityLow')}>Low-rise streets ↗</button></div><div className="district-views">{[[false,'Before'],[true,'After']].map(([enabled,label])=><button key={label} disabled={!ready} aria-pressed={quality===enabled} onClick={()=>{setQuality(enabled);api.current?.quality(enabled);}}>{label}</button>)}</div><small>Citywide detail: tower lobbies and roofs, low-rise stoops and shops. Same wallets and camera.</small></div>}<span className="district-eyebrow">{geographic?'ORIGINAL CITY GRID':`SAME ${wallets.length.toLocaleString()} WALLETS / TWO CITY DESIGNS`}</span><div className="district-layouts">{!geographic&&Object.entries(DESIGNS).map(([k,d])=><button key={k} disabled={!ready} aria-pressed={key===k} onClick={()=>choose(k)}><b>{k==='compact'?'01':'02'}</b><span>{d.name}<small>{k==='compact'?'Four neighbors per landmark':'Eight neighbors per landmark'}</small></span></button>)}</div>
 <div className="district-metrics"><div><strong>{layouts[key].blocks.length}</strong><small>{geographic?'occupied blocks':'tower blocks'}</small></div><div><strong>{key==='compact'?'1.00×':(layouts.garden.area/layouts.compact.area).toFixed(2)+'×'}</strong><small>land footprint</small></div><div><strong>12</strong><small>landmarks</small></div></div><p className="district-note">{geographic?'Towers, brownstones and courtyard blocks; 12 iconic landmarks;':'34 silhouette families, 12 iconic landmarks,'} {wallets.length.toLocaleString()} real wallets. {geographic?'Original wallet positions and continuous streets.':'Explore the mix at eight or sixteen towers per block.'}</p>
 {full&&<p className="district-note">{geographic?'Real coastlines, existing neighborhood assignments. Manhattan towers, lower-rise outer boroughs, Central Park and the harbor.':'Population scale test on an expanded study grid. Stable façades at every distance; borough geography is not applied yet.'}</p>}<span className="district-eyebrow">EXPLORE THE DISTRICT</span><div className="district-views">{[['district','District'],['landmarks','Landmarks'],['street','Street level'],['plan','From above']].map(([v,l])=><button key={v} disabled={!ready} aria-pressed={view===v} onClick={()=>frame(v)}>{l}</button>)}</div>
 {geographic&&<div className="district-views">{['manhattan','brooklyn','queens','bronx','jersey','park','bridge','harbor','exchanges','uniswap'].map(v=><button key={v} disabled={!ready} aria-pressed={view===v} onClick={()=>frame(v)}>{v==='exchanges'?'Exchange docks':v==='uniswap'?'Uniswap Island':v==='jersey'?'Jersey City':v.charAt(0).toUpperCase()+v.slice(1)}</button>)}</div>}<div className="district-light">{['day','dusk','night'].map(t=><button key={t} disabled={!ready} aria-pressed={time===t} onClick={()=>{setTime(t);api.current?.lighting(t);}}>{t}</button>)}<label><input type="checkbox" checked={traffic} onChange={e=>{setTraffic(e.target.checked);api.current?.traffic(e.target.checked);}}/>Traffic</label></div>
 {full&&<><span className="district-eyebrow">BUY / SELL TREATMENT</span><div className="district-views">{[['windows','Windows'],['edges','Edges'],['accents','Accents']].map(([mode,label])=><button key={mode} disabled={!ready} aria-pressed={signal===mode} onClick={()=>{setSignal(mode);api.current?.signal(mode);}}>{label}</button>)}</div><small>Green: adding · Rose: reducing. Accents trace cornices and upper corners. Quiet wallets retain age-colored windows.</small></>}
 <form className="district-search" onSubmit={find}><input aria-label="Find wallet in the district" placeholder="Find a wallet address" value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={!ready}>↗</button></form>{searchMessage&&<small role="status">{searchMessage}</small>}
 <p className="district-note">Mouse: drag to pan · Right-drag to orbit. Trackpad: slide to orbit · Pinch to zoom.</p><details><summary>Visit a landmark</summary><label className="district-import"><input type="checkbox" checked={imported} onChange={e=>{setImported(e.target.checked);api.current?.imported(e.target.checked);}}/> Compare downloaded Empire model</label><div className="district-landmarks">{LANDMARKS.map((l,i)=><button key={l.id} disabled={!ready} onClick={()=>focus(wallets[i])}>{l.name} ↗</button>)}</div><a className="phone-review-link" href="/review-district-mobile.html">Phone layout preview ↗</a></details>
 <details><summary>Explore {familySamples.length} building families</summary><div className="district-landmarks">{familySamples.map(w=><button key={w.identity.silhouette} disabled={!ready} onClick={()=>focus(w)}>{w.identity.name} ↗</button>)}</div></details>
 <details className="district-study-tools"><summary>Exports & study views</summary><div className="district-header-actions"><a href="/?intro=1" style={{color:"#d4e2b9",alignSelf:"center",fontSize:11}}>2.0 introduction ↗</a><a href={geographic?'/?district=1&population=1':'/?district=1&geography=1'} style={{color:"#d4e2b9",alignSelf:"center",fontSize:11}}>{geographic?'Population grid ↗':'New York geography ↗'}</a><a href={full?'/?district=1':'/?district=1&population=1'} style={{color:"#d4e2b9",alignSelf:"center",fontSize:11}}>{full?'384-wallet study ↗':'Full population ↗'}</a><a href="/?catalogue=1" style={{color:"#d4e2b9",alignSelf:"center",fontSize:11}}>50 silhouettes ↗</a><button hidden={geographic} disabled={!ready||exporting} onClick={saveComparison}>{exporting?'Rendering comparison…':'Save comparison ↗'}</button><button disabled={!ready} onClick={exportView}>Save view ↗</button><button aria-label="Close district" onClick={onClose}>✕</button></div></details>
 </aside>
 {selected&&<aside className="district-wallet"><button aria-label="Close wallet" onClick={()=>setSelected(null)}>✕</button><span className="district-eyebrow">{selected.landmark?'A CITY LANDMARK':'YOUR BUILDING'}</span><h2>{selected.landmark?LANDMARKS.find(l=>l.id===selected.landmark).name:selected.identity.name}</h2><code>{selected.a}</code>{selected.identity.character&&<p>{selected.identity.character}</p>}<p>{fmt(selected.bal)} SPX <span>· {selected.days} days held</span></p><small className={selected.flow>0?'district-buy':selected.flow<0?'district-sell':''}>{selected.flow>0?'+':''}{fmt(selected.flow)} SPX net change / 30 days</small><WalletPreview key={selected.a} address={selected.a}/></aside>}
 <footer><span>{wallets.length.toLocaleString()} real wallets · Snapshot {snapshot.updated} · A proposed district layout</span><span className="district-legend"><i/>Adding <i/>Reducing <b/>Holding age</span><span>{stats?`${stats.fps} FPS · ${stats.calls} draws · ${fmt(stats.triangles)} triangles${full?` · ${stats.detail} stable façades`:""}`:'Loading'} <a href="/models/ATTRIBUTION.md" target="_blank" rel="noreferrer">Credits ↗</a></span></footer>
 {error&&ready&&<div className="district-loading">{error}</div>}
 </section>;
}
