import React,{useEffect,useRef,useState} from 'react';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import snapshot from './fullcity/wallets.json';
import {cohort} from './district/model.js';
import {geographicLayout} from './district/geography.js';
import {createDistrict} from './district/renderer.js';
import {flypassRoute,FLYPASS_DURATION} from './district/flypass-route.js';
import './cinematic.css';
export default function Flypass(){const mount=useRef(),canvas=useRef(),api=useRef(),layout=useRef(),[ready,setReady]=useState(false),[status,setStatus]=useState('Preparing the full city…'),[busy,setBusy]=useState(false),[position,setPosition]=useState(0),record=useRef(null),raf=useRef(null);
 const draw=t=>{const shot=flypassRoute(layout.current,t),source=api.current.filmFrame(shot.position,shot.target,t,shot.roll),c=canvas.current,g=c.getContext('2d');g.drawImage(source,0,0,c.width,c.height);const fade=Math.max(0,1-Math.min(shot.local,shot.length-shot.local)/.65);g.fillStyle=`rgba(10,18,20,${fade})`;g.fillRect(0,0,c.width,c.height);g.fillStyle='#0b1518';g.fillRect(0,0,1920,64);g.fillRect(0,1016,1920,64);g.fillStyle='#e5e9db';g.font='20px Arial';g.fillText('SPX CITY 2.0',64,40);g.textAlign='right';g.fillStyle='#b8c8b1';g.fillText(shot.chapter,1856,40);g.textAlign='left';g.fillStyle='#a4b5a7';g.font='16px Arial';g.fillText('A skyline that belongs to you.',64,1055);if(t>FLYPASS_DURATION-4){g.fillStyle=`rgba(10,18,20,${Math.min(.48,(t-(FLYPASS_DURATION-4))*.12)})`;g.fillRect(0,64,1920,952);g.fillStyle='#edf0e4';g.font='64px Georgia';g.fillText('Every wallet. A place in the skyline.',180,830);}setPosition(t);};
 useEffect(()=>{let live=true,models=[];const loader=new GLTFLoader();Promise.all(['empire','liberty'].map(n=>loader.loadAsync('/models/'+n+'-optimized.glb'))).then(gs=>{models=gs;if(!live)return;const l=geographicLayout(cohort(snapshot,true));l.flowMax=Math.max(1,...l.homes.map(w=>Math.abs(w.flow)));layout.current=l;api.current=createDistrict(mount.current,{compact:l,garden:l},gs[0].scene,{liberty:gs[1].scene,onSelect:()=>{},onStats:()=>{},onError:setStatus});api.current.quality(true);draw(.8);setStatus('84-second continuous fly-through · 1080p · silent');setReady(true);}).catch(e=>setStatus(e.message));return()=>{live=false;cancelAnimationFrame(raf.current);if(record.current?.state==='recording')record.current.stop();api.current?.dispose();models.forEach(g=>g.scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose?.();}));};},[]);
 const play=async save=>{if(busy)return;setBusy(true);let recorder,stream,chunks=[];if(save){stream=canvas.current.captureStream(30);const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8'].find(m=>MediaRecorder.isTypeSupported(m));recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12000000});record.current=recorder;recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mime});try{const r=await fetch('http://127.0.0.1:5182/film',{method:'POST',body:blob});if(!r.ok)throw Error('Save failed');setStatus('Video saved to workspace.');}catch{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SPX-City-2.0-flypass.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setStatus('Video downloaded.');}setBusy(false);};recorder.start(1000);}
 setStatus(save?'Recording the flight… keep this tab visible.':'Flying…');const start=performance.now();const tick=now=>{const t=Math.min(FLYPASS_DURATION,(now-start)/1000);draw(t);if(t<FLYPASS_DURATION)raf.current=requestAnimationFrame(tick);else if(recorder)recorder.stop();else{setBusy(false);setStatus('Flight complete.');}};raf.current=requestAnimationFrame(tick);};
 return <div className="city-film"><header><a href="/?district=1&geography=1&quality=1">SPX CITY</a><span>THE CITY / A FILM</span><a href="/?district=1&geography=1&quality=1">Explore the city ↗</a></header><canvas ref={canvas} width="1920" height="1080" aria-label="Cinematic fly-through of SPX City"/><div className="film-controls"><button disabled={!ready||busy} onClick={()=>play(false)}>Play fly-through</button><button disabled={!ready||busy} onClick={()=>play(true)}>Export video</button><button disabled={!ready||busy} onClick={()=>draw(58)}>Preview turns</button><input aria-label="Flight position" type="range" min="0" max={FLYPASS_DURATION-.1} step=".1" disabled={!ready||busy} value={position} onChange={e=>draw(Number(e.target.value))}/><time>{position.toFixed(0)} / {FLYPASS_DURATION}s</time></div><p role="status" className="film-note">{status}</p><div ref={mount} style={{position:'fixed',left:-3000,top:0,width:1920,height:1080}}/></div>;
}
