import React,{useEffect,useMemo,useState} from 'react';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {LANDMARKS} from './landmarks.js';
import Skyline3D from './fullcity/Skyline3D.jsx';
import snapshot from './fullcity/wallets.json';
import {cityTowers,summarizeActivity} from './fullcity/activity.js';
import {placeCity,cityScale,HOOD_BY_ID} from './fullcity/city-map.js';
import './fullcity.css';
const fmt=n=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
export default function FullCity({onClose,initialActivity=false}){
 const [activity,setActivity]=useState(initialActivity),[win,setWin]=useState(30),[selected,setSelected]=useState(null),[asset,setAsset]=useState(null),[imported,setImported]=useState(false),[study,setStudy]=useState(true),[time,setTime]=useState('dusk'),[liberty,setLiberty]=useState(null),[cameraPreset,setCameraPreset]=useState('midtown'),[traffic,setTraffic]=useState(true),[focus,setFocus]=useState(null),[focusNonce,setFocusNonce]=useState(0),[loadError,setLoadError]=useState('');
 const [viewH,setViewH]=useState(window.innerHeight-116);
 useEffect(()=>{const resize=()=>setViewH(window.innerHeight-116);window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[]);
 useEffect(()=>{let alive=true;new GLTFLoader().load('/models/empire-optimized.glb',g=>{if(alive)setAsset(g.scene);else g.scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});},undefined,()=>alive&&setLoadError('Imported model unavailable. Original landmark is shown.'));return()=>{alive=false;};},[]);
 useEffect(()=>{let alive=true;new GLTFLoader().load('/models/liberty-optimized.glb',g=>{if(alive)setLiberty(g.scene);else g.scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});});return()=>{alive=false;};},[]);
 useEffect(()=>()=>liberty?.traverse(o=>{o.geometry?.dispose();o.material?.dispose();}),[liberty]);
 useEffect(()=>()=>asset?.traverse(o=>{o.geometry?.dispose();o.material?.dispose();}),[asset]);
 const towers=useMemo(()=>cityTowers(snapshot,win),[win]);
 const ranked=useMemo(()=>[...towers].sort((a,b)=>b.score-a.score),[towers]);
 const placed=useMemo(()=>placeCity(ranked,cityScale(ranked.length)),[ranked]);
 const neighborhoods=useMemo(()=>summarizeActivity(placed),[placed]);
 const active=towers.filter(t=>t.flow!==0).length;
 const inspect=t=>setSelected(t);
 return <section className="full-city" role="dialog" aria-label="Full city visual study">
  <header><div><small>SPX CITY / {activity?'AFTER DARK':'STUDY 03 / EXPANDED'}</small><h2>{activity?'Where the city moves.':'A living New York.'}</h2></div><nav><button className={!activity?'chosen':''} onClick={()=>{setActivity(false);setFocus(null);}}>Skyline</button><button className={activity?'chosen':''} onClick={()=>{setActivity(true);setFocus(null);setSelected(null);}}>Activity map</button><button aria-label="Close full city" onClick={onClose}>✕</button></nav></header>
  <div className="full-city-canvas"><Skyline3D towers={towers} isMobile={window.innerWidth<700} intro={false} study={study} libertyAsset={liberty} cameraPreset={cameraPreset} time={activity?'night':time} activity={activity} empireAsset={imported?asset:null} traffic={traffic} viewH={viewH} onSelect={inspect} focus={focus} focusNonce={focusNonce} cardHtml={t=>`<strong>${t.a.slice(0,8)}…${t.a.slice(-6)}</strong><br/>${fmt(t.flow)} SPX net change · ${win} days`} /></div>
  <aside className="city-controls"><span className="city-eyebrow">NET BALANCE CHANGE</span><div className="city-window">{[1,7,30].map(w=><button key={w} aria-pressed={win===w} className={win===w?'chosen':''} onClick={()=>{setWin(w);setSelected(null);}}>{w} day{w>1?'s':''}</button>)}</div>
  {activity?<><p>One parcel. One wallet.</p><div className="activity-key"><span><i className="green"/>Adding</span><span><i className="red"/>Reducing</span><span><i className="quiet"/>Quiet</span></div><div className="activity-ramp"/><small>Smaller change → larger change<br/>Logarithmic brightness · relative to this window</small><p className="activity-count">{active.toLocaleString()} <small>moving / {towers.length.toLocaleString()} wallets</small></p><div className="city-eyebrow" style={{marginTop:20}}>MOST MOVEMENT</div><div className="hood-list">{neighborhoods.slice(0,6).map(n=><div key={n.id}><span>{HOOD_BY_ID[n.id]?.name??({bronx:"The Bronx",brooklyn:"Brooklyn",queens:"Queens",jersey:"Jersey City"}[n.id]??n.id)}<small>{n.active} of {n.count} wallets moving</small></span><span><b className="adding">+{fmt(n.adding)}</b><b className="reducing">−{fmt(n.reducing)}</b></span></div>)}</div><small>Neighborhood totals sum wallet net changes, not trading volume. Drag to pan · scroll to zoom · select a parcel.</small></>:<><div className="city-window"><button className={study?'chosen':''} onClick={()=>setStudy(true)}>Study 03</button><button className={!study?'chosen':''} onClick={()=>setStudy(false)}>Original</button></div><div className="city-window">{['day','dusk','night'].map(t=><button key={t} className={time===t?'chosen':''} onClick={()=>setTime(t)}>{t}</button>)}</div><div className="city-window">{['overview','midtown','neighborhood','park','harbor'].map(t=><button key={t} className={cameraPreset===t?'chosen':''} onClick={()=>{setCameraPreset(t);setFocus(null);}}>{t==='neighborhood'?'Street blocks':t}</button>)}</div><p>4,825 individual buildings.</p><small>50 architectural types · 12 landmark silhouettes · the existing wallet layout</small><label><input type="checkbox" checked={imported} disabled={!asset} onChange={e=>setImported(e.target.checked)}/> Imported Empire State Building</label><button className="focus-landmark" onClick={()=>{setFocus(ranked[0].a);setFocusNonce(n=>n+1);}}>Inspect leading landmark ↗</button><label><input type="checkbox" checked={traffic} onChange={e=>setTraffic(e.target.checked)}/> Ambient street traffic</label><small>Traffic is decorative. Buy/sell beams retain the production thresholds.</small><p>{loadError||(!asset?'Loading landmark…':'Imported model ready for comparison.')}</p><small>Every building now uses the Study 03 architecture. Landmark designs follow score rank; wallet eligibility, positions and signals retain their existing rules.</small><div className="landmark-jumps">{LANDMARKS.map((l,i)=><button key={l.id} onClick={()=>{setFocus(ranked[i].a);setFocusNonce(n=>n+1);}}>{l.name} ↗</button>)}</div></>}
  </aside>
  {selected&&<aside className="activity-selected"><button aria-label="Close wallet details" onClick={()=>setSelected(null)}>✕</button><small>WALLET PARCEL</small><code>{selected.a}</code><h3 className={selected.flow>0?'adding':selected.flow<0?'reducing':''}>{selected.flow>0?'+':''}{fmt(selected.flow)} SPX</h3><p>Net change over {win} day{win>1?'s':''}</p><span>{fmt(selected.bal)} SPX held · {selected.days} days old</span></aside>}
  <footer><span>6900 / THE CITY IS ITS HOLDERS</span><span>Snapshot {snapshot.updated} · {towers.length.toLocaleString()} eligible wallets · <a href="/models/ATTRIBUTION.md" target="_blank" rel="noreferrer">Model credits</a></span></footer>
 </section>;
}
