import React,{useEffect,useRef,useState} from 'react';
import {X,ArrowUpRight} from 'lucide-react';
import {createHarbor} from './harbor.js';
export default function Harbor({onClose}){
 const mount=useRef(),api=useRef(),[view,setView]=useState('liberty'),[error,setError]=useState(''),[saved,setSaved]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{try{api.current=createHarbor(mount.current,setStatus);}catch(e){setError(e.message);}const key=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>{api.current?.dispose();document.removeEventListener('keydown',key);};},[]);
 return <section className="harbor-overlay" aria-label="New York harbor landmark study"><div ref={mount} className="scene"/>
 <header className="harbor-head"><div><span className="eyebrow">NEW YORK / THE HARBOR</span><h2>{view==='liberty'?'Liberty. Forever.':view==='bridge'?'A bridge between chains.':view==='park'?'The city’s green heart.':view==='bethesda'?'Meet at Bethesda.':'An unmistakable place.'}</h2></div><button className="icon-btn" onClick={onClose} aria-label="Close harbor"><X/></button></header>
 <nav className="harbor-nav">{[['liberty','Statue of Liberty'],['bridge','Brooklyn Bridge'],['park','Central Park'],['bethesda','Bethesda Fountain'],['map','Geographic context']].map(([key,label])=><button key={key} className={view===key?'active':''} aria-pressed={view===key} onClick={()=>{setView(key);api.current?.focus(key);}}>{label}</button>)}<button onClick={async()=>{try{await api.current.capture(view);setSaved(true);setTimeout(()=>setSaved(false),2500);}catch(e){setError(e.message);}}}>{saved?'Saved':'Export this view'}</button></nav>
 <aside className="harbor-note"><span className="eyebrow">{view==='liberty'?'THE BURN · 0x…dead':view==='bridge'?'WORMHOLE · BASE + SOLANA':view==='park'||view==='bethesda'?'CENTRAL PARK / LANDSCAPE STUDY':'SOURCE MAP ANCHORS'}</span><p>{view==='liberty'?'A licensed 3D scan replaces the geometric stand-in. Scanned by GoMeasure3D from a physical Statue of Liberty model; simplified and recolored for this city.':view==='bridge'?'A 1,834 m bridge with a 486 m main span, slender towers, continuous roadway, supported approaches and ground-level street connections.':view==='park'||view==='bethesda'?'A planted landscape with the Reservoir, the Lake, open lawns, winding paths, Bow Bridge and Bethesda Terrace’s tiered fountain.':'Liberty, the bridge and Central Park use the repository’s geographic projection. The wallet neighborhood remains a separate staged architecture study.'}</p><small>Authored landscape details and bridge approaches are illustrative, not a surveyed reconstruction.</small></aside>
 {view==='liberty'&&<div className="model-status" role="status">{status}</div>}
 {error&&<p className="harbor-note">{error}</p>}
 <footer className="harbor-credit"><a href="https://spx6900rainbow.xyz" target="_blank" rel="noreferrer">Source: SPX6900 Rainbow <ArrowUpRight size={11}/></a><a href="https://sketchfab.com/3d-models/6807cf4a3c8748aeb34acebd5debe649" target="_blank" rel="noreferrer">Liberty: GoMeasure3D</a><a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0 · modified</a><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a></footer></section>;
}
