import {harborSites} from './harbor-infrastructure.js';
import {cameraApproach} from './camera-approach.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {districtWorld} from './world.js';
export function createDistrict(el,layouts,asset,{onSelect,onStats,onError,liberty}){
 const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 let pixel=Math.min(devicePixelRatio,innerWidth<700?1:1.4);renderer.setPixelRatio(pixel);el.appendChild(renderer.domElement);
 const camera=new THREE.PerspectiveCamera(40,1,1,8000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.panSpeed=.9;controls.minDistance=4;controls.maxDistance=6000;controls.maxPolarAngle=Math.PI*.47;controls.mouseButtons={LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};
 const coarse=matchMedia('(pointer: coarse)').matches;
 controls.touches={ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN};
 const off=new THREE.Vector3(),spherical=new THREE.Spherical();
 const onWheel=e=>{if(!controls.enabled)return;e.preventDefault();off.copy(camera.position).sub(controls.target);const zoom=e.ctrlKey||e.shiftKey||e.deltaMode!==0||(e.deltaX===0&&Math.abs(e.deltaY)>=40);if(zoom){const factor=e.ctrlKey?Math.exp(e.deltaY*.004):Math.pow(.95,-e.deltaY*.02);off.setLength(THREE.MathUtils.clamp(off.length()*factor,controls.minDistance,controls.maxDistance));}else{spherical.setFromVector3(off);spherical.theta-=e.deltaX*.005;spherical.phi=THREE.MathUtils.clamp(spherical.phi+e.deltaY*.005,.12,controls.maxPolarAngle);off.setFromSpherical(spherical);}camera.position.copy(controls.target).add(off);controls.update();};
 if(!coarse){controls.screenSpacePanning=false;controls.enableZoom=false;renderer.domElement.addEventListener('wheel',onWheel,{passive:false});}
 let filmMode=false;
 let signalMode='accents',qualityEnabled=!!layouts.compact.geographic;
 function applyQuality(){if(!world)return;world.quality.group.visible=qualityEnabled;world.lod?.quality?.(qualityEnabled);const day=time==='day';renderer.toneMappingExposure=time==='night'?.85:time==='dusk'?.98:qualityEnabled?.96:1.04;world.scene.environmentIntensity=time==='dusk'?.6:day&&qualityEnabled?.72:1;world.sun.intensity=time==='night'?1:time==='dusk'?2.6:qualityEnabled?2.4:2.8;for(const light of world.scene.children){if(light.isAmbientLight&&day)light.intensity=qualityEnabled?.16:.32;if(light.isHemisphereLight&&day)light.intensity=qualityEnabled?.72:.95;}}
 let key='compact',time='dusk',world=null,raf,stopped=false,traffic=true,imported=false,view='district',frames=0,start=performance.now(),last=0,slow=0;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function build(){world?.dispose();world=null;renderer.renderLists.dispose();world=districtWorld(renderer,layouts[key],time,asset,imported,liberty);renderer.toneMappingExposure=time==='night'?.85:time==='dusk'?.98:1.04;world.traffic(0);world.lod?.signal?.(signalMode);applyQuality();if(view==='plan')world.scene.fog=null;}
 function frame(which='district',address){view=which;if(world)world.scene.fog=which==='plan'?null:world.fog;const layout=layouts[key];let target,offset;
 if(address){const w=layout.homes.find(w=>w.a===address);target=new THREE.Vector3(w.x,w.h*.5,w.z);offset=new THREE.Vector3(w.h*.9+4,w.h*.65+4,w.h*1.3+6);}
 else if(layout.geographic&&which==='harbor'){const p=layout.project(-52,-101);target=new THREE.Vector3(p.x,0,p.z);offset=new THREE.Vector3(95,115,145);}
 else if(layout.geographic&&['exchanges','uniswap'].includes(which)){const p=harborSites(layout)[which];target=new THREE.Vector3(p.x,2,p.z);offset=which==='exchanges'?new THREE.Vector3(45,38,58):new THREE.Vector3(36,34,50);}
 else if(which==='qualityLow'&&layout.geographic){const b=layout.blocks.find(b=>b.borough==='brooklyn'&&b.homes.length>=6);target=new THREE.Vector3(b.x,1.5,b.z);offset=new THREE.Vector3(16,12,19);}
 else if(which==='qualityStreet'&&world.quality.block){const b=world.quality.block;target=new THREE.Vector3(b.x+6,1.2,b.z+b.d/2);offset=new THREE.Vector3(12,5.5,7);}
 else if(which==='quality'&&world.quality.block){const b=world.quality.block;target=new THREE.Vector3(b.x,5,b.z);offset=new THREE.Vector3(22,26,20);}
 else if(layout.geographic&&(which==='landmarks'||which==='street')){const home=which==='landmarks'?layout.homes[0]:layout.homes.find(w=>w.block===world.quality.block?.id);const shot=cameraApproach(layout,home,which==='street');target=shot.target;offset=shot.position.clone().sub(target);}
 else if(which==='landmarks'){const a=layout.homes[0],b=layout.homes[1];target=new THREE.Vector3((a.x+b.x)/2,7,(a.z+b.z)/2);offset=new THREE.Vector3(-28,25,-42);}
 else if(which==='street'){const b=layout.geographic?layout.blocks.find(b=>b.hood==='midtown'):layout.blocks.at(-2);target=new THREE.Vector3(b.x,3,b.z);offset=new THREE.Vector3(-10,12,18);}
 else if(which==='plan'){target=new THREE.Vector3(layout.centerX||0,0,(layouts.compact.minZ+layouts.compact.maxZ)/2);offset=new THREE.Vector3(0,Math.max(layouts.compact.depth,layouts.compact.width/camera.aspect)*1.5,.001);}
 else if(layout.geographic && ['manhattan','brooklyn','queens','bronx','jersey','park','harbor','bridge'].includes(which)){const homes=layout.homes.filter(w=>w.borough===which);if(homes.length){target=new THREE.Vector3(homes.reduce((s,w)=>s+w.x,0)/homes.length,4,homes.reduce((s,w)=>s+w.z,0)/homes.length);offset=new THREE.Vector3(80,120,160);}else{const ring=which==='park'?layout.park[0]:null;target=ring?new THREE.Vector3(ring.reduce((s,p)=>s+p[0],0)/ring.length,0,ring.reduce((s,p)=>s+p[1],0)/ring.length):new THREE.Vector3((which==='bridge'?layout.bridge:layout.harbor).x,0,(which==='bridge'?layout.bridge:layout.harbor).z);offset=which==='bridge'?new THREE.Vector3(45,35,60):which==='harbor'?new THREE.Vector3(26,20,38):new THREE.Vector3(80,120,160);}}
 else {target=new THREE.Vector3(layout.centerX||0,4,(layout.minZ+layout.maxZ)/2);offset=new THREE.Vector3(layout.width*.86,layout.depth*.75,layout.depth*.98);}
 if(el.clientWidth/el.clientHeight<1 && !address)offset.multiplyScalar(el.clientWidth<500 && which==='landmarks'?1.65:1.3);camera.position.copy(target).add(offset);controls.target.copy(target);controls.update();world?.quality.update?.(camera.position,performance.now(),innerWidth<700?110:180,true);
 }
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(el);resize();build();frame(layouts[key].geographic?'manhattan':'district');
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down;
 const onDown=e=>{down=[e.clientX,e.clientY];};const onUp=e=>{if(e.button!==0||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=el.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(world.pickMesh)[0];onSelect(hit?world.picks[hit.instanceId]:null);};
 renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onUp);
 const lost=e=>{e.preventDefault();stopped=true;onError('Graphics context interrupted. Close and reopen the district.');};renderer.domElement.addEventListener('webglcontextlost',lost);
 function tick(now){if(stopped)return;raf=requestAnimationFrame(tick);if(filmMode)return;if(document.hidden){last=0;return;}const dt=last?now-last:16;last=now;controls.update();if(!reduced)world.waterMotion?.(now);if(traffic&&!reduced)world.traffic(now/1000);
 // Keep a bounded shadow region around the camera target, at a common scale for both layouts.
 const target=controls.target;world.sun.target.position.copy(target);world.sun.position.copy(target).add(world.sunOffset);
 world.lod?.update(camera.position,now,innerWidth<700?12:24);world.quality.update?.(camera.position,now,innerWidth<700?110:180);
 renderer.render(world.scene,camera);frames++;if(dt>40&&dt<500)slow+=dt;else slow=Math.max(0,slow-20);if(slow>1500&&pixel>.8){pixel=Math.max(.8,pixel*.85);renderer.setPixelRatio(pixel);resize();slow=0;}
 if(now-start>1200){onStats({fps:Math.round(frames*1000/(now-start)),calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,pixel:pixel.toFixed(2),detail:world.lod?.count??layouts[key].homes.length});frames=0;start=now;}}
 raf=requestAnimationFrame(tick);
 return {filmFrame(position,target,seconds,roll=0){filmMode=true;controls.enabled=false;camera.position.copy(position);camera.lookAt(target);camera.rotateZ(roll);camera.near=.3;camera.aspect=16/9;camera.updateProjectionMatrix();if(renderer.domElement.width!==1920){renderer.setPixelRatio(1);renderer.setSize(1920,1080,false);}world.sun.target.position.copy(target);world.sun.position.copy(target).add(world.sunOffset);world.traffic(seconds);world.waterMotion?.(seconds*1000);world.lod?.update(camera.position,performance.now(),24);world.quality.update?.(camera.position,performance.now(),180);renderer.render(world.scene,camera);return renderer.domElement;},quality(value){qualityEnabled=value;applyQuality();},signal(value){signalMode=value;world.lod?.signal?.(value);},cinematicFrames(){const images={};for(const shot of ['manhattan','landmarks','park','harbor']){frame(shot);world.sun.target.position.copy(controls.target);world.sun.position.copy(controls.target).add(world.sunOffset);renderer.render(world.scene,camera);images[shot]=renderer.domElement.toDataURL('image/png');}return images;},layout(value){key=value;build();if(view==='street')frame('street');onSelect(null);},lighting(value){time=value;build();},imported(value){imported=value;build();},view:frame,traffic(value){traffic=value;},focus(address){frame('wallet',address);},comparison(){
 const saved={key,view,position:camera.position.clone(),target:controls.target.clone()},images=[];
 try{frame('plan');for(const variant of ['compact','garden']){key=variant;build();renderer.render(world.scene,camera);images.push({key,url:renderer.domElement.toDataURL('image/png')});}return images;}
 finally{key=saved.key;view=saved.view;build();camera.position.copy(saved.position);controls.target.copy(saved.target);controls.update();}
 },capture(){renderer.render(world.scene,camera);return renderer.domElement.toDataURL('image/png');},dispose(){stopped=true;cancelAnimationFrame(raf);ro.disconnect();renderer.domElement.removeEventListener('wheel',onWheel);controls.dispose();world.dispose();renderer.dispose();renderer.domElement.removeEventListener('pointerdown',onDown);renderer.domElement.removeEventListener('pointerup',onUp);renderer.domElement.removeEventListener('webglcontextlost',lost);renderer.domElement.remove();}};
}
