// Shared, cached loader for /history.json — the daily on-chain snapshot bank
// (price, holders, cost basis, supply tiers, F&G). Several charts need it;
// this fetches it once per session and hands everyone the same promise.
// Resolves to [] on any failure so callers can treat "no data" uniformly.
let promise = null;

export function loadHistory() {
  if (!promise) {
    promise = fetch("/history.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return promise;
}

// Shared, cached loader for /price-history.json — the DENSE daily price series
// (built in CI from all price sources, weekly-refreshed) the charts draw from,
// so the early history isn't the ~weekly cadence of the model-fit bundle. Same
// []-on-failure contract; the drawn line falls back to the bundle if it's absent.
let cohortPromise = null;
// Cohort survival summary (a few KB, built daily from the city timeline) — who still holds SPX by
// arrival era. Read by the Survivorship chart; small enough to fetch eagerly on that page.
export function loadCohortSurvival() {
  if (!cohortPromise) {
    cohortPromise = fetch("/cohort-survival.json")
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d?.overall?.everHeld > 0 && Array.isArray(d.cohorts) ? d : null))
      .catch(() => null);
  }
  return cohortPromise;
}

// Whale-cohort counts over time (a few KB, built daily from the city timeline) — how many wallets
// sit in each size cohort, week by week. Read by the "Whale Counts Over Time" chart.
let whaleHistPromise = null;
export function loadWhaleCohortHistory() {
  if (!whaleHistPromise) {
    whaleHistPromise = fetch("/whale-cohort-history.json")
      .then(r => (r.ok ? r.json() : null))
      .then(d => (Array.isArray(d?.rows) && d.rows.length && Array.isArray(d.labels) ? d : null))
      .catch(() => null);
  }
  return whaleHistPromise;
}

let cityHistPromise = null;
export function loadCityHistory() {
  if (!cityHistPromise) {
    cityHistPromise = fetch("/city-history.json")
      .then(r => (r.ok ? r.json() : null))
      .then(d => (Array.isArray(d?.rows) && d.rows.length && Array.isArray(d.labels) ? d : null))
      .catch(() => null);
  }
  return cityHistPromise;
}

let exitFlowPromise = null;
export function loadExitFlow() {
  if (!exitFlowPromise) {
    exitFlowPromise = fetch("/exit-flow.json")
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d?.overall?.left > 0 && Array.isArray(d.days) ? d : null))
      .catch(() => null);
  }
  return exitFlowPromise;
}

let smartMoneyPromise = null;
export function loadSmartMoney() {
  if (!smartMoneyPromise) {
    // Members get the granular version (per-wallet addresses + buy/sell lots) from KV; the public file
    // is aggregate-only (no wallets[]), which the X card + the anonymized aggregate views still use.
    smartMoneyPromise = fetchPrivate("smart-money", "/smart-money.json", { publicSafe: true })
      .then(d => (d?.cohortSize > 0 && Array.isArray(d.weeks) ? d : null))
      .catch(() => null);
  }
  return smartMoneyPromise;
}

let pricePromise = null;
export function loadPriceHistory() {
  if (!pricePromise) {
    pricePromise = fetch("/price-history.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return pricePromise;
}

// Shared, cached loader for /longshort.json — the daily futures POSITIONING bank
// (Hyperliquid on-chain funding + open interest; CEX L/S is geo-blocked from CI).
// Data-gated: fills in as the daily banker accumulates. []-on-failure.
let lsPromise = null;
export function loadLongShort() {
  if (!lsPromise) {
    lsPromise = fetch("/longshort.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return lsPromise;
}

// Shared, cached loader for /btc-mvrv.json — Bitcoin's ~decade of MVRV history
// (Coin Metrics community API, banked monthly in CI) used as the CONTEXT backdrop
// for SPX6900's short MVRV. Resolves to { points: [] } on any failure so callers
// can treat "no data yet" uniformly (the bundle is generated by the btc-mvrv workflow).
let btcMvrvPromise = null;
let freeFloatPeersPromise = null;
// BTC + ETH free float (liquid supply %) vs days-since-inception — Coin Metrics community,
// banked by the freefloat-peers workflow. Resolves to { btc, eth } arrays (empty on any error).
export function loadFreeFloatPeers() {
  if (!freeFloatPeersPromise) {
    freeFloatPeersPromise = fetch("/freefloat-peers.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => ({ btc: d?.btc || [], eth: d?.eth || [] }))
      .catch(() => ({ btc: [], eth: [] }));
  }
  return freeFloatPeersPromise;
}

export function loadBtcMvrv() {
  if (!btcMvrvPromise) {
    btcMvrvPromise = fetch("/btc-mvrv.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.points) ? d : { points: [] }))
      .catch(() => ({ points: [] }));
  }
  return btcMvrvPromise;
}

// Shared, cached loader for /onchain.json — the SPX6900 on-chain valuation &
// distribution WEEKLY series (Supply in Profit %, concentration, gini, HODL waves),
// re-executed from Dune weekly in CI (build-onchain.mjs). Resolves to null on any
// failure so callers can fall back to the bundled src/spx-onchain.js.
// Cached loader for /cohort-roi.json — lifetime ROI by whale size band (% in profit + typical
// multiple), rebuilt daily off the timeline in onchain-dune.yml. Null on failure.
let cohortRoiPromise = null;
export function loadCohortRoi() {
  if (!cohortRoiPromise) {
    cohortRoiPromise = fetch("/cohort-roi.json")
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.cohorts) ? d : null))
      .catch(() => null);
  }
  return cohortRoiPromise;
}

// Cached loader for /whale-entry.json — when each ≥100k whale bought (entry date × avg cost) + bag +
// in-profit, plus the SPX price curve for the backdrop. Rebuilt daily in onchain-dune.yml.
let whaleEntryPromise = null;
export function loadWhaleEntry() {
  if (!whaleEntryPromise) {
    // Members get the granular version (each whale's address, for the Zerion links) from KV; the public
    // file has the addresses stripped — the orb field + curve still render for the card / aggregate.
    whaleEntryPromise = fetchPrivate("whale-entry", "/whale-entry.json", { publicSafe: true })
      .then(d => (d && Array.isArray(d.whales) && Array.isArray(d.curve) ? d : null))
      .catch(() => null);
  }
  return whaleEntryPromise;
}

// Cached loader for /whale-lots.json — per-wallet buy/sell lots for EVERY ≥100k whale (same shape as
// smart-money.json's wallets[]), so the per-wallet page opens for any orb, not just the smart-money
// cohort. Members-only (addresses + lots): the public committed copy has wallets[] stripped, so this is
// NOT publicSafe — it resolves only for members (KV). Rebuilt daily in onchain-dune.yml.
let whaleLotsPromise = null;
export function loadWhaleLots() {
  if (!whaleLotsPromise) {
    whaleLotsPromise = fetchPrivate("whale-lots", "/whale-lots.json")
      .then(d => (d && Array.isArray(d.wallets) && d.wallets.length ? d : null))
      .catch(() => null);
  }
  return whaleLotsPromise;
}

let onchainPromise = null;
export function loadOnchain() {
  if (!onchainPromise) {
    onchainPromise = fetch("/onchain.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (Array.isArray(d) && d.length ? d : null))
      .catch(() => null);
  }
  return onchainPromise;
}

// THE DATA WALL — address-revealing feeds are served ONLY to logged-in members from the private store
// (KV, via /api/auth?action=data&f=<feed>), not from the public repo/site. `fetchPrivate` reads the
// authed endpoint first; during a feed's cutover it falls back to the still-committed public file so
// nothing breaks while KV is being seeded. Once a feed's public file is removed, the fallback simply
// 404s and only members (through the authed endpoint) get the data. A 403 (not a member) returns null.
// `publicSafe` = the committed public file is an anonymized/aggregate version that is SAFE to serve to
// anyone (e.g. whales.json with addresses stripped). Then a 403 (not a member) falls back to it, so
// public charts + the X cards keep working while members get the granular KV version. When it's false
// (entities, spx-timeline — no safe public copy) a 403 returns null: truly members-only.
export async function fetchPrivate(feed, publicPath, { publicSafe = false } = {}) {
  try {
    const r = await fetch(`/api/auth?action=data&f=${feed}`, { cache: "no-cache" });
    if (r.ok) return await r.json();               // member — served the granular version from KV
    if (r.status === 403 && !publicSafe) return null;   // not a member + nothing safe to fall back to
    // 403 (publicSafe) / 404 (not published yet) / 503 (store off) / "not configured" → public file
  } catch { /* network — fall back */ }
  if (!publicPath) return null;
  try { const r = await fetch(publicPath, { cache: "no-cache" }); return r.ok ? await r.json() : null; }
  catch { return null; }
}

// Shared, cached loader for the entity-clustering graph (Phase 2/3): which wallets belong to one owner,
// reconstructed from SPX drain/fund flows. An OBJECT { updated, spot, heldSupply, method, params, stats,
// entities:[{id, size, bal, holders, flagged, wallets, edges}] }. Members-only (real addresses).
let entitiesPromise = null;
export function loadEntities() {
  if (!entitiesPromise) {
    entitiesPromise = fetchPrivate("entities", "/entities.json")
      .then(d => (d && Array.isArray(d.entities) ? d : null))
      .catch(() => null);
  }
  return entitiesPromise;
}

// Shared, cached loader for /aeon-onchain.json — the Project Aeon NFT holder
// reconstruction (owners, holder-age/HODL waves, concentration, flow), an OBJECT
// { updated, supply, current, series }. Null on failure → bundled AEON_ONCHAIN.
let aeonPromise = null;
export function loadAeon() {
  if (!aeonPromise) {
    aeonPromise = fetch("/aeon-onchain.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.series) && d.series.length ? d : null))
      .catch(() => null);
  }
  return aeonPromise;
}

// Shared, cached loader for /cex-sankey.json — the exchange flow map (who supplies/withdraws from
// exchanges + exchange candidates). Null until the daily onchain-dune run writes it.
let cexSankeyPromise = null;
export function loadCexSankey() {
  if (!cexSankeyPromise) {
    cexSankeyPromise = fetch("/cex-sankey.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && d.totals && (d.inflow?.length || d.outflow?.length) ? d : null))
      .catch(() => null);
  }
  return cexSankeyPromise;
}

// Shared, cached loader for /aeon-sales.json — the Aeon marketplace floor/volume series
// (daily floor ETH+USD, volume, per-sale scatter). Null on failure → bundled AEON_SALES.
let aeonSalesPromise = null;
export function loadAeonSales() {
  if (!aeonSalesPromise) {
    aeonSalesPromise = fetch("/aeon-sales.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.daily) && d.daily.length ? d : null))
      .catch(() => null);
  }
  return aeonSalesPromise;
}

// Shared, cached loader for /aeon-rarity.json — the Project Aeon trait-rarity data
// (per-token rank/score/traits + trait-frequency tables). ~1.35MB → fetch-only (not
// bundled); the rarity chart is lazy-loaded so it never touches the base bundle.
let aeonRarityPromise = null;
export function loadAeonRarity() {
  if (!aeonRarityPromise) {
    aeonRarityPromise = fetch("/aeon-rarity.json", { cache: "force-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.tokens) && d.tokens.length ? d : null))
      .catch(() => null);
  }
  return aeonRarityPromise;
}

// Shared, cached loader for /aeon-listings.json — active OpenSea listings joined to
// rarity (the deal-finder feed). Null on failure so the chart shows an empty state.
let aeonListPromise = null;
export function loadAeonListings() {
  if (!aeonListPromise) {
    aeonListPromise = fetch("/aeon-listings.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.listings) && d.listings.length ? d : null))
      .catch(() => null);
  }
  return aeonListPromise;
}

// Aeon market valuation (MVRV / supply-in-profit / URPD / deals / biggest sales / trait premiums).
let aeonMktPromise = null;
export function loadAeonMarket() {
  if (!aeonMktPromise) aeonMktPromise = fetch("/aeon-market.json", { cache: "no-cache" }).then(r => r.ok ? r.json() : null).then(d => d && d.valuation ? d : null).catch(() => null);
  return aeonMktPromise;
}
// Aeon trader intelligence (wallet P&L leaderboard).
let aeonTradersPromise = null;
export function loadAeonTraders() {
  if (!aeonTradersPromise) aeonTradersPromise = fetch("/aeon-traders.json", { cache: "no-cache" }).then(r => r.ok ? r.json() : null).then(d => d && Array.isArray(d.top) ? d : null).catch(() => null);
  return aeonTradersPromise;
}

// Shared, cached loader for /urpd.json — the cost-basis distribution snapshot (URPD)
// from the local FIFO engine. Resolves to null on failure so the caller falls back to
// the bundled src/spx-urpd.js.
let urpdPromise = null;
export function loadUrpd() {
  if (!urpdPromise) {
    urpdPromise = fetch("/urpd.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.buckets) && d.buckets.length ? d : null))
      .catch(() => null);
  }
  return urpdPromise;
}

// Shared, cached loader for /urpd-history.json — weekly cost-basis slices on one fixed price grid
// (the URPD terrain). Resolves null on failure so the 3D chart data-gates until the pipeline banks it.
let urpdHistPromise = null;
export function loadUrpdHistory() {
  if (!urpdHistPromise) {
    urpdHistPromise = fetch("/urpd-history.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.weeks) && d.weeks.length ? d : null))
      .catch(() => null);
  }
  return urpdHistPromise;
}

// Shared, cached loader for /whales.json — the biggest CURRENT holders with how much each has
// added or shed over the lookback windows (from the FIFO engine; CEX/LP/bridge already excluded,
// so these are real holders). Resolves to null on failure — the whale watcher then data-gates.
let whalesPromise = null;
export function loadWhales() {
  if (!whalesPromise) {
    // PUBLIC: whales.json powers SPX City (a public showpiece) + its per-building Zerion cards, so it
    // carries addresses openly (raw top-holder addresses are already visible on any explorer; the
    // proprietary LINKAGE is what stays members-only via entities.json).
    whalesPromise = fetch("/whales.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.wallets) && d.wallets.length ? d : null))
      .catch(() => null);
  }
  return whalesPromise;
}

// Persistent whale sell-campaigns (7-day-idle earmark, cumulative footprint) — daily cron.
// Resolves to null (never throws) so the board falls back to the on-view live feed / static grid.
let whaleCampaignsPromise = null;
export function loadWhaleCampaigns() {
  if (!whaleCampaignsPromise) {
    whaleCampaignsPromise = fetch("/whale-campaigns.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.wallets) ? d : null))
      .catch(() => null);
  }
  return whaleCampaignsPromise;
}

// Solana / Base ≥5k residents (balance, holder age, 30-day net flow) — daily reconstruction. Used by
// the whale board's per-chain sections. Resolve to null on failure (that chain just doesn't show).
let solanaOnchainPromise = null;
export function loadSolanaOnchain() {
  if (!solanaOnchainPromise) {
    solanaOnchainPromise = fetch("/solana-onchain.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.wallets) ? d : null))
      .catch(() => null);
  }
  return solanaOnchainPromise;
}

let baseOnchainPromise = null;
export function loadBaseOnchain() {
  if (!baseOnchainPromise) {
    baseOnchainPromise = fetch("/base-onchain.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.wallets) ? d : null))
      .catch(() => null);
  }
  return baseOnchainPromise;
}

// Shared, cached loader for /cex-flow.json — daily CEX/LP/custody balances + flow (Dune baseline
// + daily snapshot-forward). Resolves to null on failure so callers fall back to src/cex-flow.js.
let cexFlowPromise = null;
export function loadCexFlow() {
  if (!cexFlowPromise) {
    cexFlowPromise = fetch("/cex-flow.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.days) && d.days.length ? d : null))
      .catch(() => null);
  }
  return cexFlowPromise;
}

// Shared, cached loader for /chain-wallets.json — multi-chain weekly wallet counts
// (ETH+Base+Solana), refreshed by chain-wallets.yml. Resolves to null on any failure so
// callers fall back to the bundled src/chain-wallets.js.
let chainWalletsPromise = null;
export function loadChainWallets() {
  if (!chainWalletsPromise) {
    chainWalletsPromise = fetch("/chain-wallets.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (Array.isArray(d) && d.length ? d : null))
      .catch(() => null);
  }
  return chainWalletsPromise;
}

// Shared, cached loader for /valuation.json — the weighted valuation composite
// (over/under-valued oscillator + today's weighted lens breakdown), regenerated
// daily by the snapshot cron. Resolves to null on any failure so the chart can
// show a graceful "being computed" state.
let valuationPromise = null;
export function loadValuation() {
  if (!valuationPromise) {
    valuationPromise = fetch("/valuation.json", { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.series) && d.series.length ? d : null))
      .catch(() => null);
  }
  return valuationPromise;
}

// Friendly copy for live-API failures. The raw error (JSON parse noise, proxy
// statuses) is meaningless to visitors — never show it in the UI.
export const LIVE_DATA_DOWN = "Live data is temporarily unavailable — try again in a minute.";

// City time-machine data: weekly per-wallet balances (sparse change-points), one file per asset.
// BIG (SPX ~3MB) and only wanted when someone opens the slider, so it is fetched lazily with the
// browser's default caching (Vercel etags make revisits a 304, and the file changes only daily).
const timelinePromises = {};
export function loadCityTimeline(asset) {
  const file = asset === "aeon" ? "/aeon-timeline.json" : "/spx-timeline.json";
  const f = asset === "aeon" ? "aeon" : "spx";
  if (!timelinePromises[f]) {
    // PUBLIC: the SPX City time machine is part of the public showpiece, so its timeline is public too.
    timelinePromises[f] = fetch(file, { cache: "no-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.wallets) && d.n > 0 ? d : null))
      .catch(() => null);
  }
  return timelinePromises[f];
}
